### ISSUE TITLE
Does boiler come from PCDB flag

### ISSUE THREAD

**Issue by GlennS** [cse-bristol/national-household-model-stock-files-creator#1]
In SAP 2012, there is a rule that storage losses for combi-boilers are applied differently based on how the efficiency numbers for that combi-boiler were looked up (in the PCDB, or from the default tables).

We therefore need to add a flag to say whether or not we successfully looked up a boiler in the PCDB or not.

**Comment by GlennS** [comment]
I had added the property to the technology model.

Once we have this in the DTO, we need to change the following line in HeatSourceBuilder:

boiler.setEfficiencySource(EfficiencySourceType.SAP_DEFAULT);

**Comment by trickyBytes** [comment]
#### DTO Import project
- [x] Add new expected column to the space heating dto indicating from PCDB look-up successful

#### R Stock Import Scripts
- [x] Scotland - add field to space heating dto, indicating PCDB look-up
- [x] England - add field to space heating dto, indicating PCDB look-up
- [x] Wales - check how wales uses Scottish dto for spaceheating, modify if necessary

#### Testing
- [ ] Can a stock be imported?
