### ISSUE TITLE
Shower Type

### ISSUE THREAD

**Issue by GlennS** [cse-bristol/national-household-model-stock-files-creator#2]
We need to add a field to the stock import for the shower type. 

This will be based on [BREDEM 2012](http://www.bre.co.uk/filelibrary/bredem/BREDEM-2012-specification.pdf) Table 6. 

We'll treat the two mixer shower rows as being the same for stock import purposes - the NHM energy calculator can decide between these rows itself based on whether or not there is a combi boiler present.

The BRE recommendation is to on whether or not there is a second water heating system present in the dwelling:
- Second system present -> electric shower
- Not present -> mixer shower

**Comment by trickyBytes** [comment]
Actually is, add a column to a dto for shower type, this would be either electric or mixer based on whether there is a second water heating system present or not.
- [ ] Check what second water heating system means
