### ISSUE TITLE
Thermal Mass

### ISSUE THREAD

**Issue by GlennS** [cse-bristol/national-household-model-stock-files-creator#3]
We currently implement the fairly complicated full thermal mass calculation from SAP. We probably don't have enough data to justify this.

Based on BRE's recommendation, we'll use the simplified method from [SAP 2012](http://www.bre.co.uk/filelibrary/SAP/2012/SAP-2012_9-92.pdf) table 1f instead.

We will add a field to the stock import to say whether a dwelling has low, medium or high thermal mass. This is determined based on predominant wall type and insulation as follows:

| Wall Type   | Insulation  | Thermal Mass |
|-------------+-------------+--------------|
| Stone/Solid | Insulated   | High         |
| Stone/Solid | Uninsulated | Low          |
| Timber      | Any         | Low          |
| Other       | Any         | Medium       |

We also need to take out the existing data about thermal mass (which I believe exists mainly in the imputation schema).

**Comment by trickyBytes** [comment]
### Proposed changes within the DTO and therefore r-script creation
- [ ] A column named "Thermal Mass" will be added to the cases.dto file, values will be High, Low, Medium

### Questions for Us/Glenn
- [x] Is the information on wall construction type and insulation now required at all?
- [x] Does the above mean that measure that install insulation are now meaningless?
- [x] Again are the insulation and resulting measures for roofs/lofts now required?

### Questions for BEIS (Kieran?)

#### For Scotland
- Assume predominant wall type is primary + could confirm by ensuring that that wall is assigned to most elevations
- Insulated for Solid/Stone- should this be if more than 50% of elevations are insulated then it's insulated or any wall is insulated?

**Comment by GlennS** [comment]
Changes to this:
- We don't need the thermal mass column now: we'll decide inside the energy calculator.
- We do still want to remove all the thermal mass from the imputation schema.
- We want to keep the u-values though (which is the main effect of insulation, wall type etc.)

**Comment by trickyBytes** [comment]
I've done this across the imputation schema and most of domain models, I have left compilation errors where things visitors for Energy calculation need to be altered.

Glenn to consider:
- [x] There are thermal conductivity and deckThermalResistance in the floor property tables, I'm not sure whether we should remove these too as they seem to be used on calculating the u values of floors starts at line:53 of FloorPropertyImputer#getUValue

**Comment by GlennS** [comment]
We want to keep the ones needed for the u-value calculation.

Unsure why they're in the k-value column.
